/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tarea2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;

/**
 *
 * @author trini
 */
public class Registro extends javax.swing.JFrame {
    
   Connection cx;
   Statement stmt;
   int i;


    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setTitle("Registro Vendedores");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Min_Vendidos = new javax.swing.JTextField();
        Fort_Vendidos = new javax.swing.JTextField();
        Cod_Vendidos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        DiObMin = new javax.swing.JTextField();
        DiObFort = new javax.swing.JTextField();
        DiObCod = new javax.swing.JTextField();
        CoGaMin = new javax.swing.JTextField();
        CoGaFort = new javax.swing.JTextField();
        CoGaCod = new javax.swing.JTextField();
        TotalDineroGanado = new javax.swing.JTextField();
        ComTotal = new javax.swing.JTextField();
        CantJuegos = new javax.swing.JTextField();
        NombreVendedor = new javax.swing.JTextField();
        GuardarLosDatos = new javax.swing.JButton();
        VerElRanking = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Calculos = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Registro de los Vendedores");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 10, 400, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel4.setText("Nombre del Vendedor:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 180, -1));

        Min_Vendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Min_VendidosActionPerformed(evt);
            }
        });
        Min_Vendidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Min_VendidosKeyTyped(evt);
            }
        });
        getContentPane().add(Min_Vendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 71, 30));

        Fort_Vendidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Fort_VendidosKeyTyped(evt);
            }
        });
        getContentPane().add(Fort_Vendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 71, 30));

        Cod_Vendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cod_VendidosActionPerformed(evt);
            }
        });
        Cod_Vendidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Cod_VendidosKeyTyped(evt);
            }
        });
        getContentPane().add(Cod_Vendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(908, 292, 71, 30));

        jLabel7.setText("Juegos Vendidos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 150, -1));

        jLabel8.setText("Dinero Obtenido");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 150, -1));

        jLabel9.setText("Comisión Ganada");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 150, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("Total Dinero Obtenido");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 150, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 0));
        jLabel11.setText("Comición Ganada Total");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 160, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 0));
        jLabel12.setText("Cantidad de Juevos Vendidos");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, -1, -1));

        DiObMin.setEditable(false);
        DiObMin.setBackground(new java.awt.Color(204, 255, 204));
        DiObMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiObMinActionPerformed(evt);
            }
        });
        getContentPane().add(DiObMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 71, 30));

        DiObFort.setEditable(false);
        DiObFort.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(DiObFort, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 71, 30));

        DiObCod.setEditable(false);
        DiObCod.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(DiObCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(908, 334, 71, 30));

        CoGaMin.setEditable(false);
        CoGaMin.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(CoGaMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 71, 30));

        CoGaFort.setEditable(false);
        CoGaFort.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(CoGaFort, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 71, 30));

        CoGaCod.setEditable(false);
        CoGaCod.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(CoGaCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 380, 71, 30));

        TotalDineroGanado.setEditable(false);
        TotalDineroGanado.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(TotalDineroGanado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 80, 30));

        ComTotal.setEditable(false);
        ComTotal.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(ComTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 71, 30));

        CantJuegos.setEditable(false);
        CantJuegos.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(CantJuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 430, 71, 25));

        NombreVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreVendedorKeyTyped(evt);
            }
        });
        getContentPane().add(NombreVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 169, -1));

        GuardarLosDatos.setText("Guardar los Datos");
        GuardarLosDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarLosDatosActionPerformed(evt);
            }
        });
        getContentPane().add(GuardarLosDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        VerElRanking.setText("Ver el Ranking");
        VerElRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerElRankingActionPerformed(evt);
            }
        });
        getContentPane().add(VerElRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 123, -1));

        jLabel13.setText("Juegos Vendidos");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 150, 20));

        jLabel14.setText("Dinero Obtenido");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 150, 20));

        jLabel15.setText("Comisión Ganada");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 150, 20));

        jLabel16.setText("Juegos Vendidos");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 150, -1));

        jLabel17.setText("Dinero Obtenido");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 150, -1));

        jLabel18.setText("Comisión Ganada");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 150, -1));

        Calculos.setText("Calcular datos");
        Calculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculosActionPerformed(evt);
            }
        });
        getContentPane().add(Calculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, -1, -1));

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea2/Imagenes/FORT 2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 154, 180, 73));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea2/Imagenes/COD 2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 260, 73));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea2/Imagenes/MINE 2.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setMaximumSize(new java.awt.Dimension(180, 50));
        jLabel5.setPreferredSize(new java.awt.Dimension(180, 50));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, 50));

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Valor: 8800");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Valor: 58200");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 230, 120, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Valor: 34500");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Min_VendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Min_VendidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Min_VendidosActionPerformed

    private void Cod_VendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cod_VendidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cod_VendidosActionPerformed

    private void DiObMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiObMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiObMinActionPerformed

    private void GuardarLosDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarLosDatosActionPerformed
        String nom;
        String DinMin;
        String ComMin;
        String DinFort;
        String ComFort;
        String DinCod;
        String ComCod;
        String TGanancias;
        String CObtenida;
        String JVendidos;
        
        nom = NombreVendedor.getText();
        DinMin = DiObMin.getText();        
        ComMin = CoGaMin.getText();        
        DinFort = DiObFort.getText();        
        ComFort = CoGaFort.getText();        
        DinCod = DiObCod.getText();        
        ComCod = CoGaCod.getText();        
        TGanancias = TotalDineroGanado.getText();
        CObtenida = ComTotal.getText();
        JVendidos = CantJuegos.getText();
        
        String bd = "reg_vendedores";
        String url ="jdbc:mysql://localhost:3306/"+bd+"?useSSL=false&serverTimezone=UTC";
        String user = "root";
        String password = "";
        String driver = "com.mysql.cj.jdbc.driver";
        String st = "INSERT INTO vendedores VALUES('"+nom+"','"+DinMin+"','"+ComMin+"','"+DinFort+"','"+ComFort+"','"+DinCod+"','"+ComCod+"','"+TGanancias+"','"+CObtenida+"','"+JVendidos+"')";
        try{
            //System.out.println("Hola");
            cx = DriverManager.getConnection(url,user,password);
            System.out.println("Se conecto a la base de datos: "+bd);
            stmt = cx.createStatement();
            stmt.executeUpdate(st);
            javax.swing.JOptionPane.showMessageDialog(this, "Se registró a la BD");
        } catch (SQLException ex){
            System.out.println("No se conecto a la Base de datos "+bd);
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE,null,ex);
        }
        try{
            cx.close();
        } catch (SQLException ex){
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE,null,ex);
        }
        
        
    }//GEN-LAST:event_GuardarLosDatosActionPerformed

    private void NombreVendedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreVendedorKeyTyped
        
        char c = evt.getKeyChar();
        if((c<'a' ||c>'z') &&(c<'A' ||c>'Z') &&(c<' ' ||c>' '))evt.consume();
    }//GEN-LAST:event_NombreVendedorKeyTyped

    private void Min_VendidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Min_VendidosKeyTyped
        
        char c = evt.getKeyChar();
        if(c<'0' ||c>'9')evt.consume();
    }//GEN-LAST:event_Min_VendidosKeyTyped

    private void Fort_VendidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Fort_VendidosKeyTyped

        char c = evt.getKeyChar();
        if(c<'0' ||c>'9')evt.consume();
    }//GEN-LAST:event_Fort_VendidosKeyTyped

    private void Cod_VendidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cod_VendidosKeyTyped

        char c = evt.getKeyChar();
        if(c<'0' ||c>'9')evt.consume();
    }//GEN-LAST:event_Cod_VendidosKeyTyped

    private void VerElRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerElRankingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerElRankingActionPerformed

    private void CalculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculosActionPerformed
        // TODO add your handling code here:
        double Ven_Cod = Double.parseDouble(Cod_Vendidos.getText());
        double Ven_Min = Double.parseDouble(Min_Vendidos.getText());
        double Ven_Fort= Double.parseDouble(Fort_Vendidos.getText());
        double precio_Cod = 34500;
        double precio_Min = 8800;
        double precio_Fort = 58200;
        DiObCod.setText(String.valueOf(Ven_Cod*precio_Cod));
        DiObMin.setText(String.valueOf(Ven_Min*precio_Min));
        DiObFort.setText(String.valueOf(Ven_Fort*precio_Fort));
        CoGaCod.setText(String.valueOf((Ven_Cod*precio_Cod)*0.06));
        CoGaMin.setText(String.valueOf((Ven_Min*precio_Min)*0.04));
        CoGaFort.setText(String.valueOf((Ven_Fort*precio_Fort)*0.09));
        TotalDineroGanado.setText(String.valueOf((Ven_Cod*precio_Cod)+(Ven_Min*precio_Min)+(Ven_Fort*precio_Fort)));
        double Com_Cod = Double.parseDouble(CoGaCod.getText());
        double Com_Min = Double.parseDouble(CoGaMin.getText());
        double Com_Fort = Double.parseDouble(CoGaFort.getText());
        ComTotal.setText(String.valueOf(Com_Cod+Com_Min+Com_Fort));
        CantJuegos.setText(String.valueOf(Ven_Cod+Ven_Min+Ven_Fort));
    }//GEN-LAST:event_CalculosActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
        NombreVendedor.setText("");
        Min_Vendidos.setText("");
        Cod_Vendidos.setText("");
        Fort_Vendidos.setText("");
        DiObCod.setText("");
        DiObMin.setText("");
        DiObFort.setText("");
        CoGaCod.setText("");
        CoGaMin.setText("");
        CoGaFort.setText("");
        TotalDineroGanado.setText("");
        ComTotal.setText("");
        CantJuegos.setText("");
        NombreVendedor.grabFocus();
        //JOptionPane.showmessageDialog(null,"Limpieza exitosa");
    }//GEN-LAST:event_LimpiarActionPerformed
    //1:09:20
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calculos;
    private javax.swing.JTextField CantJuegos;
    private javax.swing.JTextField CoGaCod;
    private javax.swing.JTextField CoGaFort;
    private javax.swing.JTextField CoGaMin;
    private javax.swing.JTextField Cod_Vendidos;
    private javax.swing.JTextField ComTotal;
    private javax.swing.JTextField DiObCod;
    private javax.swing.JTextField DiObFort;
    private javax.swing.JTextField DiObMin;
    private javax.swing.JTextField Fort_Vendidos;
    private javax.swing.JButton GuardarLosDatos;
    private javax.swing.JButton Limpiar;
    private javax.swing.JTextField Min_Vendidos;
    private javax.swing.JTextField NombreVendedor;
    private javax.swing.JTextField TotalDineroGanado;
    private javax.swing.JButton VerElRanking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
