/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tarea2;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author diego
 */
public class Vendedor extends javax.swing.JFrame {
    Connection cx;
    Statement stmt;
    int i;
    
    public Vendedor() {
        initComponents();
        this.setTitle("Registro vendedores");
        this.setLocation(700, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        cantCod = new javax.swing.JTextField();
        cantMin = new javax.swing.JTextField();
        cantFor = new javax.swing.JTextField();
        Ingresar = new javax.swing.JButton();
        BotonMostrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 67, -1));

        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Cant COD:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 68, -1));

        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Cant Min:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 74, -1));

        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Cant Fort:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 75, -1));

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreKeyTyped(evt);
            }
        });
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 90, -1));

        cantCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantCodActionPerformed(evt);
            }
        });
        cantCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantCodKeyTyped(evt);
            }
        });
        getContentPane().add(cantCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 90, -1));

        cantMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantMinKeyTyped(evt);
            }
        });
        getContentPane().add(cantMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 90, -1));

        cantFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantForActionPerformed(evt);
            }
        });
        cantFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantForKeyTyped(evt);
            }
        });
        getContentPane().add(cantFor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 90, -1));

        Ingresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Ingresar.setText("Ingresar");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        getContentPane().add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        BotonMostrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonMostrar.setText("Finalizar Registro");
        BotonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Actualizar dato");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/descarga (1).png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Minecraft.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fortnite.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gamer.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        String nombre;
        Integer cant_Cod, cant_Min, cant_For, cant_Tot;
        double com_Cod, com_Min, com_For, com_Tot ;
        Integer precioCod = 34500;
        Integer precioMin = 8800;
        Integer precioFor = 58200;
        double comisionCod =  0.06  ;
        double comisionMin = 0.04 ;
        double comisionFor = 0.09 ;
        
        nombre = Nombre.getText();
        cant_Cod = Integer.parseInt(cantCod.getText()) * precioCod ;
        cant_Min = Integer.parseInt(cantMin.getText()) * precioMin;
        cant_For = Integer.parseInt(cantFor.getText()) * precioFor;
        cant_Tot = cant_Cod + cant_Min + cant_For;
        
        int cantidadCod = cant_Cod;
        int cantidadMin = cant_Min;            // cambio de tipo Integer a int para poder multiplicarlos por float.
        int cantidadFor = cant_For;
        
        com_Cod = cantidadCod * comisionCod;
        com_Min = cantidadMin * comisionMin;
        com_For = cantidadFor * comisionFor;           // Cálculo de comisiones
        com_Tot = com_Cod + com_Min + com_For;
                
        
       if (((Nombre.getText().equals("") || cantCod.getText().equals("")) || cantMin.getText().equals("")) || cantFor.getText().equals("")) {
           
           javax.swing.JOptionPane.showMessageDialog(this,"Debes llenar todos los campos \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
           Nombre.requestFocus();
           
       }else{
           String bd = "personas";
           String url ="jdbc:mysql://localhost:3306/"+bd+"?useSSL=false&serverTimezone=UTC";
           String user = "root";
           String password = "";
           String driver = "com.mysql.cj.jdbc.driver";
           String st = "INSERT INTO vendedores VALUES('"+nombre+"','"+cant_Cod+"','"+cant_Min+"','"+cant_For+"','"+cant_Tot+"','"+com_Cod+"','"+com_Min+"','"+com_For+"','"+com_Tot+"')";
           
           try {
               cx = DriverManager.getConnection(url,user,password);
               System.out.println("Se conectó a la base de datos " + bd);
               stmt = cx.createStatement();
               stmt.executeUpdate(st);
               javax.swing.JOptionPane.showMessageDialog(this, "Se registró a la BD");
               this.Nombre.setText("");
               this.cantCod.setText("");
               this.cantMin.setText("");
               this.cantFor.setText("");
               
           } catch(SQLException ex){
               System.out.println("No se encontro la BD " + bd);
               Logger.getLogger(Vendedor.class.getName()).log(Level.SEVERE, null, ex);
           }
       } 
    }//GEN-LAST:event_IngresarActionPerformed

    private void NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyTyped
        char c = evt.getKeyChar();
        if ((c<'a'|| c>'z')&&(c<'A'|| c>'Z')&& (c <' ' || c >' ')) evt.consume();
    }//GEN-LAST:event_NombreKeyTyped

    private void cantCodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantCodKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_cantCodKeyTyped

    private void cantMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantMinKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_cantMinKeyTyped

    private void cantForKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantForKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_cantForKeyTyped

    private void cantForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantForActionPerformed

    private void cantCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantCodActionPerformed

    private void BotonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarActionPerformed
        mostrar_vendedores cu = null;
        cu = new mostrar_vendedores();
        cu.setLocationRelativeTo(null);
        cu.setVisible(true);

       
    }//GEN-LAST:event_BotonMostrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonMostrar;
    private javax.swing.JButton Ingresar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField cantCod;
    private javax.swing.JTextField cantFor;
    private javax.swing.JTextField cantMin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
