
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Lenovo
 */
public class usuarios extends javax.swing.JFrame {

    Connection con = null;
    Statement stmt = null;
    
    public usuarios() {
        initComponents();
        this.setTitle("Registro");
        this.setLocation(200, 100);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        lbl_fondo2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ventafornite = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_comisionfornite = new javax.swing.JTextField();
        lbl_fondo3 = new javax.swing.JLabel();
        lbl_fondo4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_VentasMinecraft = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_ComisionMinecraft = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_VentasCOD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_ComisionCOD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_VentasTotal = new javax.swing.JTextField();
        txt_Comisiontotal = new javax.swing.JLabel();
        txt_ComisionTOTAL = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        btn_Consultar = new javax.swing.JButton();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 30));

        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 290, -1));

        lbl_fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fortnite.jpg"))); // NOI18N
        getContentPane().add(lbl_fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 80, 120));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Precio: 58.200 ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ventas Fornite");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        txt_ventafornite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ventaforniteKeyTyped(evt);
            }
        });
        getContentPane().add(txt_ventafornite, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 80, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Comision Fornite");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        txt_comisionfornite.setEditable(false);
        txt_comisionfornite.setBackground(new java.awt.Color(153, 153, 153));
        txt_comisionfornite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_comisionforniteKeyTyped(evt);
            }
        });
        getContentPane().add(txt_comisionfornite, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 80, -1));

        lbl_fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1.jpg"))); // NOI18N
        getContentPane().add(lbl_fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 80, 110));

        lbl_fondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/2.jpg"))); // NOI18N
        getContentPane().add(lbl_fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 80, 110));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ventas Minecraft");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        txt_VentasMinecraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_VentasMinecraftActionPerformed(evt);
            }
        });
        txt_VentasMinecraft.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_VentasMinecraftKeyTyped(evt);
            }
        });
        getContentPane().add(txt_VentasMinecraft, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 80, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Comision Minecraft");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        txt_ComisionMinecraft.setEditable(false);
        txt_ComisionMinecraft.setBackground(new java.awt.Color(153, 153, 153));
        txt_ComisionMinecraft.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ComisionMinecraftKeyTyped(evt);
            }
        });
        getContentPane().add(txt_ComisionMinecraft, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 80, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio: 8.800");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ventas COD");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        txt_VentasCOD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_VentasCODKeyTyped(evt);
            }
        });
        getContentPane().add(txt_VentasCOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 80, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Comision COD");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        txt_ComisionCOD.setEditable(false);
        txt_ComisionCOD.setBackground(new java.awt.Color(153, 153, 153));
        txt_ComisionCOD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ComisionCODKeyTyped(evt);
            }
        });
        getContentPane().add(txt_ComisionCOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 80, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Precio: 34.500");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cantidad vendida en total");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        txt_VentasTotal.setEditable(false);
        txt_VentasTotal.setBackground(new java.awt.Color(153, 153, 153));
        txt_VentasTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_VentasTotalKeyTyped(evt);
            }
        });
        getContentPane().add(txt_VentasTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 110, -1));

        txt_Comisiontotal.setForeground(new java.awt.Color(255, 255, 255));
        txt_Comisiontotal.setText("Comision total ");
        getContentPane().add(txt_Comisiontotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        txt_ComisionTOTAL.setEditable(false);
        txt_ComisionTOTAL.setBackground(new java.awt.Color(153, 153, 153));
        txt_ComisionTOTAL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ComisionTOTALKeyTyped(evt);
            }
        });
        getContentPane().add(txt_ComisionTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 110, -1));

        btn_aceptar.setText("Guardar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, -1, -1));

        btn_Consultar.setText("Consultar");
        btn_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, -1, -1));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondotarea2.3.jpg"))); // NOI18N
        getContentPane().add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 801, 491));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_VentasMinecraftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_VentasMinecraftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_VentasMinecraftActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        
        String cadena2,cadena3,cadena4,cadena5,cadena6,cadena7,cadena8,cadena9,cadena10;
        
        cadena2 = txt_nombre.getText();
        cadena3 = txt_ventafornite.getText();
        int i=Integer.parseInt(txt_ventafornite.getText());
        int Vt=i;
        i=(int) (0.09*i*58200);
        int Ct=i;
        cadena4 =String.valueOf(i);
        cadena5 = txt_VentasCOD.getText();
        int cod=Integer.parseInt(txt_VentasCOD.getText());
        Vt=Vt+cod;
        cod=(int) (0.06*cod*34500);
        Ct=Ct+cod;
        cadena6 = String.valueOf(cod);
        cadena7 = txt_VentasMinecraft.getText();
        int mine=Integer.parseInt(txt_VentasMinecraft.getText());
        Vt=Vt+mine;
        mine=(int) (0.04*mine*8800);
        Ct=Ct+mine;
        cadena8 =String.valueOf(mine);
        cadena9 =String.valueOf(Vt);
        cadena10 =String.valueOf(Ct);
        
        
        if (txt_nombre.getText().equals("") || (txt_ventafornite.getText().equals("")) 
             || (txt_VentasCOD.getText().equals(""))
                ||  (txt_VentasMinecraft.getText().equals(""))){
                        javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            txt_nombre.requestFocus();

        }
        else {
        try {
           
            String url = "jdbc:mysql://localhost:3306/registrousuarios";
            String usuario = "root";
            String contraseña = "1234";
            
             Class.forName("com.mysql.jdbc.Driver").newInstance(); 
             con = DriverManager.getConnection(url,usuario,contraseña); 
             if ( con != null ) 
                    System.out.println("""
                                       Se ha establecido una conexi\u00f3n a la base de datos 
                                        """ + url ); 
  
                  stmt = con.createStatement(); 
                  stmt.executeUpdate("INSERT INTO usuarios VALUES('" + 0 + "','"+cadena2+"','"+cadena3+"','"+cadena4+"','"+cadena5+"','"+cadena6+"','"+cadena7+"','"+cadena8+"','"+cadena9+"','"+cadena10+"')");
                  System.out.println("Los valores han sido agregados a la base de datos ");
                  
                  
                 
                   
        } catch (InstantiationException | IllegalAccessException | ClassNotFoundException | SQLException ex) {
           Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        finally {
            if (con != null) {
                try {
                    con.close();
                    stmt.close();
                } catch ( SQLException e ) { 
                         System.out.println( e.getMessage());
                }
            }
        }
         javax.swing.JOptionPane.showMessageDialog(this,"Registro exitoso! \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        this.txt_nombre.setText("");
        this.txt_ventafornite.setText("");
        this.txt_comisionfornite.setText("");
        this.txt_VentasMinecraft.setText("");
        this.txt_ComisionMinecraft.setText("");
        this.txt_VentasCOD.setText("");
        this.txt_ComisionCOD.setText("");
        this.txt_VentasTotal.setText("");
        this.txt_ComisionTOTAL.setText("");
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        char c = evt.getKeyChar();
        if ((c<'a'|| c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' '))evt.consume();
        
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_ventaforniteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ventaforniteKeyTyped
        
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txt_ventaforniteKeyTyped

    private void txt_VentasMinecraftKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_VentasMinecraftKeyTyped
        
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txt_VentasMinecraftKeyTyped

    private void txt_VentasCODKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_VentasCODKeyTyped
        
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txt_VentasCODKeyTyped

    private void txt_comisionforniteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_comisionforniteKeyTyped
       
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txt_comisionforniteKeyTyped

    private void txt_ComisionMinecraftKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ComisionMinecraftKeyTyped
        
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txt_ComisionMinecraftKeyTyped

    private void txt_ComisionCODKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ComisionCODKeyTyped
        
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txt_ComisionCODKeyTyped

    private void txt_VentasTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_VentasTotalKeyTyped
        
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txt_VentasTotalKeyTyped

    private void txt_ComisionTOTALKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ComisionTOTALKeyTyped
        
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txt_ComisionTOTALKeyTyped

    private void btn_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultarActionPerformed
        
        try {
           
            String url = "jdbc:mysql://localhost:3306/registrousuarios";
            String usuario = "root";
            String contraseña = "1234";
            
             Class.forName("com.mysql.jdbc.Driver").newInstance(); 
             con = DriverManager.getConnection(url,usuario,contraseña); 
             if ( con != null ) 
                    System.out.println("""
                                       Se ha establecido una conexi\u00f3n a la base de datos 
                                        """ + url );
        
        Statement s = con.createStatement();
                  ResultSet rs = s.executeQuery ("select max(ventas_total) from usuarios");
                  
                  while (rs.next())
                  {
                      String Venta_Mayor;
                      Venta_Mayor =String.valueOf(rs.getInt(1));
                      
                      String Mayor_Vendedor;
                      ResultSet mv = s.executeQuery("select usuario from usuarios where ventas_total="+Venta_Mayor);
                      
                      while (mv.next())
                      {
                          Mayor_Vendedor=mv.getString(1);
                          ResultSet comgan =s.executeQuery("select com_total from usuarios where ventas_total="+Venta_Mayor);
                          while (comgan.next())
                          {
                              String Comision_Ganada;
                              Comision_Ganada=String.valueOf(comgan.getInt(1));
                              
                              javax.swing.JOptionPane.showMessageDialog(this,"El mayor vendedor es:\n"+Mayor_Vendedor+"\nCon una comision de:\n"+Comision_Ganada,"AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                          }
                          
                      }
                  }
        }
        catch (InstantiationException | IllegalAccessException | ClassNotFoundException | SQLException ex) {
           Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btn_ConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Consultar;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lbl_fondo2;
    private javax.swing.JLabel lbl_fondo3;
    private javax.swing.JLabel lbl_fondo4;
    private javax.swing.JTextField txt_ComisionCOD;
    private javax.swing.JTextField txt_ComisionMinecraft;
    private javax.swing.JTextField txt_ComisionTOTAL;
    private javax.swing.JLabel txt_Comisiontotal;
    private javax.swing.JTextField txt_VentasCOD;
    private javax.swing.JTextField txt_VentasMinecraft;
    private javax.swing.JTextField txt_VentasTotal;
    private javax.swing.JTextField txt_comisionfornite;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_ventafornite;
    // End of variables declaration//GEN-END:variables

}
