import java.sql.Connection;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.TableColumn;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;

public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.setTitle("Calculadora Ventas y Comision");
        this.setLocation(200, 200);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        nombreV = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ventas_fn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ventas_cod = new javax.swing.JTextField();
        ventas_mc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comision_cod = new javax.swing.JLabel();
        ventaP_cod = new javax.swing.JLabel();
        comision_mc = new javax.swing.JLabel();
        ventaP_mc = new javax.swing.JLabel();
        comision_fn = new javax.swing.JLabel();
        ventaP_fn = new javax.swing.JLabel();
        registrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        abrirBD = new javax.swing.JToggleButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreVActionPerformed(evt);
            }
        });
        nombreV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreVKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("N° Ventas FN");

        ventas_fn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ventas_fnKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("$58200");

        ventas_cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ventas_codKeyTyped(evt);
            }
        });

        ventas_mc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ventas_mcKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("N° Ventas MC");

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\DOCS\\uni\\2022-2\\paradigmas de programacion\\tarea 2\\img\\fn.png")); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\DOCS\\uni\\2022-2\\paradigmas de programacion\\tarea 2\\img\\cod.png")); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\DOCS\\uni\\2022-2\\paradigmas de programacion\\tarea 2\\img\\mc.png")); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("N° Ventas CoD");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("$8800");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("$34500");

        comision_cod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comision_cod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comision_cod.setText("CG");

        ventaP_cod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ventaP_cod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ventaP_cod.setText("VTP");

        comision_mc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comision_mc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comision_mc.setText("CG");

        ventaP_mc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ventaP_mc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ventaP_mc.setText("VTP");

        comision_fn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comision_fn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comision_fn.setText("CG");

        ventaP_fn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ventaP_fn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ventaP_fn.setText("VTP");

        registrar.setBackground(new java.awt.Color(153, 255, 153));
        registrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nombre");

        abrirBD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        abrirBD.setText("Abrir Base de Datos");
        abrirBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirBDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel5))
                            .addComponent(jLabel10))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreV, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ventas_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ventas_mc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(ventaP_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(ventaP_mc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(ventaP_fn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ventas_fn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(comision_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(comision_mc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(comision_fn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(abrirBD, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel5)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(nombreV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(ventas_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(ventas_mc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ventaP_cod)
                            .addComponent(ventaP_mc)
                            .addComponent(ventaP_fn))))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(ventas_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comision_cod)
                            .addComponent(comision_mc)
                            .addComponent(comision_fn))))
                .addGap(5, 5, 5)
                .addComponent(registrar)
                .addGap(53, 53, 53)
                .addComponent(abrirBD, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreVActionPerformed
     
    }//GEN-LAST:event_nombreVActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        Connection cx = null;
        Statement stmt;
        int i=0;
        String nombre;
        int vcod, vmc, vfn; //unidades vendidas
        int vtp_cod, vtp_mc, vtp_fn, vt; //ventas totales en pesos
        int cg_cod, cg_mc, cg_fn, ct; // comision ganada
        nombre = nombreV.getText();
        vcod = Integer.parseInt(ventas_cod.getText());
        vmc = Integer.parseInt(ventas_mc.getText());
        vfn = Integer.parseInt(ventas_fn.getText());
        //calcular ventas totales en pesos
        vtp_cod = (vcod * 34500); 
        vtp_mc = (vmc * 8800);
        vtp_fn = (vfn * 58200);
        vt = vtp_cod + vtp_mc + vtp_fn;
        //calcular comision ganada
        cg_cod = (int) ((34500 * 0.06) * (vcod));
        cg_mc = (int) ((8800 * 0.04) * (vmc));
        cg_fn = (int) ((58200 * 0.09) * (vfn));
        ct = cg_cod + cg_mc + cg_fn;
        //mostrar ventas
        ventaP_cod.setText("$"+String.valueOf(vtp_cod));
        ventaP_mc.setText("$"+String.valueOf(vtp_mc));
        ventaP_fn.setText("$"+String.valueOf(vtp_fn));
        //mostrar comisiones
        comision_cod.setText("$"+String.valueOf(cg_cod));
        comision_mc.setText("$"+String.valueOf(cg_mc));
        comision_fn.setText("$"+String.valueOf(cg_fn));
        // BASE DE DATOS
        String bd = "ventasjuegos";
        String url ="jdbc:mysql://localhost:3306/"+bd+"?useSSL=false&serverTimezone=UTC";
        String user="root";
        String password = "hourglas";
        String driver = "com.mysql.cj.jdbc.driver";
        String st = "INSERT INTO vendedores VALUES('"+nombre+"','"+vcod+"','"+vmc+"','"+vfn+"','"+vt+"', '"+cg_cod+"','"+cg_mc+"','"+cg_fn+"','"+ct+"')";
        try{
           // Class.forName(driver);
            cx= DriverManager.getConnection(url,user,password);
            System.out.println("Se conecto a la BD "+bd);
            stmt = cx.createStatement();
            stmt.executeUpdate(st);
            System.out.println("Se registro a la BD ");
            javax.swing.JOptionPane.showMessageDialog(this, "Se registro a la BD");
            this.nombreV.setText("");
            this.ventas_cod.setText("");
            this.ventas_mc.setText("");
            this.ventas_fn.setText("");
            i++;
        } catch (SQLException ex) {
            System.out.println("No se conecto a la BD "+bd);
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            cx.close();
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void ventas_codKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ventas_codKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_ventas_codKeyTyped

    private void ventas_mcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ventas_mcKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_ventas_mcKeyTyped

    private void ventas_fnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ventas_fnKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_ventas_fnKeyTyped

    private void nombreVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreVKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_nombreVKeyTyped

    private void abrirBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirBDActionPerformed
        new Tabla().setVisible(true);
    }//GEN-LAST:event_abrirBDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton abrirBD;
    private javax.swing.JLabel comision_cod;
    private javax.swing.JLabel comision_fn;
    private javax.swing.JLabel comision_mc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombreV;
    private javax.swing.JButton registrar;
    private javax.swing.JLabel ventaP_cod;
    private javax.swing.JLabel ventaP_fn;
    private javax.swing.JLabel ventaP_mc;
    private javax.swing.JTextField ventas_cod;
    private javax.swing.JTextField ventas_fn;
    private javax.swing.JTextField ventas_mc;
    // End of variables declaration//GEN-END:variables
}
